### PR TITLE
Fixes dmbates/MixedModels.jl#106

### PR DESCRIPTION
**Pull request by andyreagan**

### CODE REVIEW

**Comment by dmbates** [comment]
Again, thanks for the PR.  Your change doesn't really fix the problem because the original and the modified requirement are synonymous. The first version number is the lower bound and a lower bound of 0.19 is the same as a lower bound of 0.19.0.  To disallow StatsBase 0.19.2 and later you would need to put an upper bound of 0.19.1 but I would prefer not to do that.

I do not mean to discourage you from submitting pull requests.  I am just trying to explain why I will end up doing things differently.

**Comment by andyreagan** [comment]
Yeah, that makes sense! I misunderstood here:
https://docs.julialang.org/en/stable/manual/packages/#Requirements-Specification-1

I think that the conflict between statsmodels and statsbase needs to be fixed between those two groups, rather than us pinning a version that works.
Maybe I'm confused, though.

**Comment by dmbates** [comment]
@andyreagan Yes.  The solution is to release a new version of `StatsModels` that does not define `coefnames` and depends on `StatsBase 0.19.2`

**Comment by andyreagan** [comment]
Yup, seeing your comment over on StatsBase's latest release as well!

**Pull request closed without merging**
