### PR TITLE
Allow for `fit` to be used

### PR DESCRIPTION
**Pull request by Nosferican**
Allows for `StatsBase.fit` method.

### CODE REVIEW

**Comment by dmbates** [comment]
@Nosferican Were you intending also to add a `fit!` method for `LinearMixedModel`?

**Comment by Nosferican** [comment]
I was more focused on doing the `fit(GeneralizedLinearMixedModel, ...)` method.
Right now one doesn't need to do the `fit(LinearMixedModel, ...)` since by omitting the link it is smart and creates the correct implied model if not mistaken. I think
```
fit!(model::LinearMixedModel, ....)
```
isn't necessary for end-users, but it is implemented since the `GeneralizedLinearMixedModel` has the `LinearMixedModel` as a field. I think I saw that. Do let me know your thoughts and I can check the PR for it after rebasing it.

**Comment by Nosferican** [comment]
This should be ready for review.

**Comment by Nosferican** [comment]
The 32-bit infrastructure issue on Windows seems unrelated. Probably worth investigating after this PR.

**Pull request merged**
